upstream backend {
    server 172.17.0.3:3000;
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

        proxy_cache api_cache;
        proxy_cache_valid 200 30s;
        proxy_cache_use_stale error timeout;
        add_header X-Cache-Status $upstream_cache_status;
        limit_rate 200k;
        
        proxy_pass http://backend/;
    }

}